"""initial schema

Revision ID: 26681b25eb53
Revises: 
Create Date: 2026-08-19 13:43:29.799930
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import app.models.base


revision: str = '26681b25eb53'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('logo', sa.String(length=500), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('categories',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=500), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('contact_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('submitted_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_requests_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_requests_handled'), ['handled'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_requests_submitted_at'), ['submitted_at'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('designation', sa.String(length=50), nullable=False),
    sa.Column('custom_designation', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('access_options', app.models.base.JSONVariant(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id_number')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=True)

    op.create_table('gmail_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('connected_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_images',
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('slot')
    )
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=60), nullable=False),
    sa.Column('tracking_id', sa.String(length=60), nullable=False),
    sa.Column('items', app.models.base.JSONVariant(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('delivery_option', sa.String(length=30), nullable=False),
    sa.Column('delivery_option_name', sa.String(length=120), nullable=False),
    sa.Column('delivery_eta', sa.String(length=120), nullable=False),
    sa.Column('preferred_date', sa.String(length=10), nullable=False),
    sa.Column('address', app.models.base.JSONVariant(), nullable=False),
    sa.Column('placed_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('order_number')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_customer_name'), ['customer_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_placed_at'), ['placed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_tracking_id'), ['tracking_id'], unique=False)

    op.create_table('quotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('items', app.models.base.JSONVariant(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('details', app.models.base.JSONVariant(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('customer_email', sa.String(length=320), nullable=False),
    sa.Column('submitted_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotations_customer_email'), ['customer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_quotations_submitted_at'), ['submitted_at'], unique=False)

    op.create_table('daily_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('submitted_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reports_employee_id'), ['employee_id'], unique=False)

    op.create_table('leave_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_employee_id'), ['employee_id'], unique=False)

    op.create_table('order_confirmations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('ref_number', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('issued_date', sa.String(length=10), nullable=False),
    sa.Column('tracking_id', sa.String(length=60), nullable=False),
    sa.Column('lines', app.models.base.JSONVariant(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('terms', app.models.base.JSONVariant(), nullable=False),
    sa.Column('issued_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('delivery_stage', sa.Integer(), nullable=False),
    sa.Column('delivery_updated_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_id')
    )
    with op.batch_alter_table('order_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_confirmations_issued_at'), ['issued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_confirmations_tracking_id'), ['tracking_id'], unique=True)

    op.create_table('products',
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('part_number', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('brand', sa.String(length=160), nullable=False),
    sa.Column('category_slug', sa.String(length=160), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('gallery', app.models.base.JSONVariant(), nullable=False),
    sa.Column('short_specs', app.models.base.JSONVariant(), nullable=False),
    sa.Column('description', app.models.base.JSONVariant(), nullable=False),
    sa.Column('alternate_part_numbers', app.models.base.JSONVariant(), nullable=False),
    sa.Column('specifications', app.models.base.JSONVariant(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.String(length=20), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('warranty_years', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_slug'], ['categories.slug'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('slug')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category_slug'), ['category_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_part_number'), ['part_number'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assignee_employee_id', sa.String(length=36), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assignee_employee_id'), ['assignee_employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_assignee_employee_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_part_number'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_category_slug'))
        batch_op.drop_index(batch_op.f('ix_products_brand'))

    op.drop_table('products')
    with op.batch_alter_table('order_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_confirmations_tracking_id'))
        batch_op.drop_index(batch_op.f('ix_order_confirmations_issued_at'))

    op.drop_table('order_confirmations')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_employee_id'))

    op.drop_table('leave_requests')
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reports_employee_id'))

    op.drop_table('daily_reports')
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotations_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_quotations_status'))
        batch_op.drop_index(batch_op.f('ix_quotations_customer_email'))

    op.drop_table('quotations')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_tracking_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_placed_at'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_name'))

    op.drop_table('orders')
    op.drop_table('hero_images')
    op.drop_table('gmail_token')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_email'))

    op.drop_table('employees')
    with op.batch_alter_table('contact_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_requests_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_contact_requests_handled'))
        batch_op.drop_index(batch_op.f('ix_contact_requests_email'))

    op.drop_table('contact_requests')
    op.drop_table('categories')
    op.drop_table('brands')
    # ### end Alembic commands ###
