"""invoices and challans

Revision ID: a8c7bdab8852
Revises: a1c93f27e04b
Create Date: 2026-08-26 01:01:38.857135
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# Custom column types (UTCDateTime, JSONVariant) are referenced by autogenerate.
import app.models.base


revision: str = 'a8c7bdab8852'
down_revision: str | None = 'a1c93f27e04b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('challan_number', sa.String(length=100), nullable=True),
    sa.Column('challan_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=60), nullable=False),
    sa.Column('driver_info', sa.String(length=200), nullable=False),
    sa.Column('receiver_name', sa.String(length=200), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('signed_document_url', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('approved_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challan_number')
    )
    with op.batch_alter_table('challans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_challans_quotation_id'), ['quotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challans_status'), ['status'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quotation_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('other_charges', sa.Float(), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('approved_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_quotation_id'), ['quotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)

    op.create_table('challan_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('challan_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('specifications', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challan_id'], ['challans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challan_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_challan_lines_challan_id'), ['challan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_challan_lines_slug'), ['slug'], unique=False)

    op.create_table('invoice_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('specifications', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_lines_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_lines_slug'), ['slug'], unique=False)

    op.create_table('invoice_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=False),
    sa.Column('received_at', app.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_payments_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_payments_invoice_id'))

    op.drop_table('invoice_payments')
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_lines_slug'))
        batch_op.drop_index(batch_op.f('ix_invoice_lines_invoice_id'))

    op.drop_table('invoice_lines')
    with op.batch_alter_table('challan_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challan_lines_slug'))
        batch_op.drop_index(batch_op.f('ix_challan_lines_challan_id'))

    op.drop_table('challan_lines')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_created_at'))

    op.drop_table('invoices')
    with op.batch_alter_table('challans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_challans_status'))
        batch_op.drop_index(batch_op.f('ix_challans_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_challans_created_at'))

    op.drop_table('challans')
    # ### end Alembic commands ###
